on: [push]
name: test coverage
jobs:
  test_coverage:
    name: test coverage
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.3' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test --coverage
      - run: stack hpc report . --destdir output
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: output
